version: '3.8'

services:

    app:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            -"3000:3000"
        environment:
            - DATABASE_URL=postgresql://user_admin:super_secret_password@postgres_db:5432/my_app_db?schema=public
            - NEXT_PUBLIC_SOCKET_URL=http://localhost:3000
        depends_on:
            postgres_db:
                condition: service_healthy
        restart: always
    postgres_db:
    image: postgres:15-alpine
    environment:
    - POSTGRES_USER=user_admin
    - POSTGRES_PASSWORD=super_secret_password
    - POSTGRES_DB=my_app_db
    ports:
        -"5432:5432"
    volumes:
        - pg_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL","pg_isready -U user_admin -d my_app_db"]
        interval: 5s
        timeout: 5s
        retries: 5
    restart: always
volumes:
    pg_data:
