# Base Image
FROM node:18-alpine

# Working Directory
WORKDIR /app

#Copy files from computer into container
COPY . .

#Install project dependancies
RUN npm install

# Port the container listens on
EXPOSE 3000

# Define the command to run the app when the container start
CMD ["node", "server.js"]