#Multi Stage Build

# Stage 1: The build environment

FROM golang:1.21-alpine AS builder
WORKDIR /src

# Copy dependancy files first
COPY go.mod go.sum ./
RUN go mod download

# Copy rest of source code
COPY . .

#Compile the binary file into a single, highly binary file named 'server'
RUN CGO_ENABLED=0 GOOS=linux go build -o server

# Stage 2: The Production Environment

FROM alpine:latest
WORKDIR /app
#Pulls only the finished binary from builder
COPY --from=builder /src/server 

EXPOSE 8080

CMD [ "./server" ]
