  name: CI/CD pipeline

  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]
  jobs:
    # Job1: test and lint(CI)
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v4

        - name: Setup node.js runtime
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'npm'
        
        - name: install dependancies
          run: npm ci

        - name: Run linting
          run: npm run lint
        
        - name: Run test
          run: npm test
    
    deploy:
      needs: test
      if: github.ref =='refs/heads/main' && github.event_name == 'push'
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v4
        
        - name: Build production artifacts
          run: |
            npm ci
            npm run build
        - name: Deploy to cloud provider
          env:
            API_KEY: ${{ secrets.PROD_API_KEY }}
          run: ./scripts/deploy.sh


      

